/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JsonLdId, JsonLdObject} from "@think-it-labs/edc-connector-client";

export class PartnerGroup extends JsonLdId {

}

export interface PartnerGroupInput {
    "@id"?: string;
    "tx:groups"?: string[];
  }