# Stage 1: Compile and Build angular codebase
FROM node:lts as build

WORKDIR /app
COPY ./ /app/
COPY ./src/environments/environment.provider.ts /app/src/environments/environment.test.ts

RUN npm install
RUN npm run build

# Stage 2: Serve app with nginx
FROM nginx:alpine
COPY --from=build /app/deployment/common/nginx.common.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/edc-demo-client /usr/share/nginx/html
COPY --from=build /app/src/assets /usr/share/nginx/html/assets
# Added 2025.8.12

RUN chmod +x /usr/share/nginx/html/assets/config/entrypoint.sh
ENTRYPOINT ["/usr/share/nginx/html/assets/config/entrypoint.sh"]

# Added 2025.2.19
#COPY ./ssl/certfile.pem /etc/nginx/ssl/certfile.pem
#COPY ./ssl/keyfile.pem /etc/nginx/ssl/keyfile.pem
EXPOSE 80

HEALTHCHECK --interval=2s --timeout=5s --retries=10 \
  CMD curl -f http://localhost/ || exit 1
