events {}
http {
  include /etc/nginx/mime.types;
  server {
      listen       80;
      server_name  localhost;

      root   /usr/share/nginx/html;
      index  index.html;

      location / {
          try_files $uri $uri/ /index.html;
      }

      location /management {
        resolver 127.0.0.11 valid=30s;
        set $upstream_consumer http://consumer-connector:9193/management;
        proxy_pass $upstream_consumer;
      }
  }
}
